export const SET_USER = "SET_USER"
export const UNSET_USER = "UNSET_USER"
export const SAVE_VENUES = "SAVE_VENUES"
export const REMOVE_ALL_INTERESTS ='REMOVE_ALL_INTERESTS'
export const ADD_CONCERT_INTEREST = 'ADD_CONCERT_INTEREST'
export const REMOVE_CONCERT_INTEREST ='REMOVE_CONCERT_INTEREST'
